# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(307, 203)
        self.gridLayout = QtWidgets.QGridLayout(login)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_login_username = QtWidgets.QLineEdit(login)
        self.txt_login_username.setObjectName("txt_login_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_login_username)
        self.label_3 = QtWidgets.QLabel(login)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txt_login_password = QtWidgets.QLineEdit(login)
        self.txt_login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_login_password.setObjectName("txt_login_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_login_password)
        self.btn_login = QtWidgets.QPushButton(login)
        self.btn_login.setObjectName("btn_login")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_login)
        self.label = QtWidgets.QLabel(login)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label)
        self.gridLayout.addLayout(self.formLayout, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.label_2.setText(_translate("login", "Username"))
        self.label_3.setText(_translate("login", "Password"))
        self.btn_login.setText(_translate("login", "Login"))
        self.label.setText(_translate("login", "Please enter the username \n"
"and password correctly"))
