# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backup_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Config(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.configs_backup_btn_cancel = QtWidgets.QPushButton(Dialog)
        self.configs_backup_btn_cancel.setObjectName("configs_backup_btn_cancel")
        self.horizontalLayout.addWidget(self.configs_backup_btn_cancel)
        self.configs_backup_btn_save = QtWidgets.QPushButton(Dialog)
        self.configs_backup_btn_save.setObjectName("configs_backup_btn_save")
        self.horizontalLayout.addWidget(self.configs_backup_btn_save)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Backup Configuration"))
        self.label.setText(_translate("Dialog", "Please enter the discription"))
        self.configs_backup_btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.configs_backup_btn_save.setText(_translate("Dialog", "Save"))
